### ISSUE TITLE
Address Manager Migration #8 causes OOM

### ISSUE THREAD

**Issue by davidcaseria** [btcsuite/btcwallet#629]
Running lnd on a raspberrypi now causes an out of memory error because of the latest database migration:
```
Jul 02 18:18:36 ubuntu lnd[24426]: 2019-07-02 18:18:36.238 [INF] LNWL: Applying wallet address manager migration #8
Jul 02 18:18:36 ubuntu lnd[24426]: 2019-07-02 18:18:36.239 [INF] LNWL: Removing block hash entries beyond maximum reorg depth of 10000 from current tip 583488
Jul 02 18:18:39 ubuntu lnd[24426]: fatal error: runtime: out of memory
Jul 02 18:18:39 ubuntu lnd[24426]: runtime stack:
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.throw(0xc92c15, 0x16)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/panic.go:617 +0x54
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.sysMap(0x4008000000, 0x10000000, 0x191be98)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/mem_linux.go:170 +0xc0
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.(*mheap).sysAlloc(0x19032a0, 0x10000000, 0x19032b0, 0x8000)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/malloc.go:633 +0x168
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.(*mheap).grow(0x19032a0, 0x8000, 0x0)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/mheap.go:1222 +0x38
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.(*mheap).allocSpanLocked(0x19032a0, 0x8000, 0x191bea8, 0x34474)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/mheap.go:1150 +0x37c
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.(*mheap).alloc_m(0x19032a0, 0x8000, 0xffff7e1e0101, 0xffff8e2bee08)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/mheap.go:977 +0xc0
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.(*mheap).alloc.func1()
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/mheap.go:1048 +0x48
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.(*mheap).alloc(0x19032a0, 0x8000, 0x4000010101, 0xffff7e19dea0)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/mheap.go:1047 +0x6c
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.largeAlloc(0x10000000, 0xffff8e2b0101, 0x4001e49b00)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/malloc.go:1055 +0x94
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.mallocgc.func1()
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/malloc.go:950 +0x44
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.systemstack(0x0)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/asm_arm64.s:237 +0xa0
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.mstart()
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/proc.go:1153
Jul 02 18:18:39 ubuntu lnd[24426]: goroutine 43 [running]:
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.systemstack_switch()
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/asm_arm64.s:182 +0x8 fp=0x40004a8fc0 sp=0x40004a8fb0 pc=0x696f8
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.mallocgc(0x10000000, 0xa68200, 0xffff81d73a01, 0x4002522000)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/malloc.go:949 +0x75c fp=0x40004a9080 sp=0x40004a8fc0 pc=0x1b79c
Jul 02 18:18:39 ubuntu lnd[24426]: runtime.makeslice(0xa68200, 0x4000000, 0x4000000, 0x4002522000)
Jul 02 18:18:39 ubuntu lnd[24426]:         /usr/local/go/src/runtime/slice.go:49 +0x78 fp=0x40004a90b0 sp=0x40004a9080 pc=0x545a8
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/golangcrypto/scrypt.Key(0x40002e23c0, 0x10, 0x10, 0x4002509688, 0x20, 0x20, 0x40000, 0x8, 0x1, 0x20, ...)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/golangcrypto@v0.0.0-20150304025918-53f62d9b43e8/scrypt/scrypt.go:235 +0xd0 fp=0x40004a9160 sp=0x40004a90b0 pc=0x350f80
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/snacl.(*SecretKey).deriveKey(0x4002509680, 0x40004a9698, 0x20, 0xa77c00)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/snacl/snacl.go:114 +0x70 fp=0x40004a9200 sp=0x40004a9160 pc=0x351700
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/snacl.(*SecretKey).DeriveKey(0x4002509680, 0x40004a9698, 0x58, 0x58)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/snacl/snacl.go:201 +0x30 fp=0x40004a9270 sp=0x40004a9200 pc=0x351af0
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/waddrmgr.loadManager(0xffff8623f178, 0x40001de440, 0x40002e23c0, 0x10, 0x10, 0x18d2fc0, 0x400001e000, 0xb24320, 0xbf4440)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/waddrmgr/manager.go:1443 +0x240 fp=0x40004a9680 sp=0x40004a9270 pc=0x3655f0
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/waddrmgr.Open(0xffff8623f178, 0x40001de440, 0x40002e23c0, 0x10, 0x10, 0x18d2fc0, 0xb190a0, 0x40000b80a8, 0x400030c0e0)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/waddrmgr/manager.go:1530 +0x60 fp=0x40004a9730 sp=0x40004a9680 pc=0x366000
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/wallet.Open.func1(0xfa2fc0, 0x40000b80a8, 0x40000b80a8, 0x0)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/wallet/wallet.go:3550 +0x204 fp=0x40004a97f0 sp=0x40004a9730 pc=0x4ff544
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/walletdb.Update(0xf98de0, 0x40002e8400, 0x40004a9910, 0x4000312180, 0x40002e8400)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/walletdb/interface.go:225 +0x60 fp=0x40004a9850 sp=0x40004a97f0 pc=0x34d2c0
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/wallet.Open(0xf98de0, 0x40002e8400, 0x40002e23c0, 0x10, 0x10, 0x40004a9a08, 0x18d2fc0, 0x0, 0x40004a99e8, 0x4e466c, ...)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/wallet/wallet.go:3533 +0x94 fp=0x40004a9950 sp=0x40004a9850 pc=0x4f5054
Jul 02 18:18:39 ubuntu lnd[24426]: github.com/btcsuite/btcwallet/wallet.(*Loader).OpenExistingWallet(0x40001e29c0, 0x40002e23c0, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0)
Jul 02 18:18:39 ubuntu lnd[24426]:         /Users/roasbeef/gocode/pkg/mod/github.com/btcsuite/btcwallet@v0.0.0-20190628225330-4a9774585e57/wallet/loader.go:189 +0x2e8 fp=0x40004a9a50 sp=0x40004a9950 pc=0x4e43b8
```

**Comment by davidcaseria** [comment]
After adding 1GB of swap memory was able to successfully run the migration.
