### ISSUE TITLE
panic: Unable to synchronize wallet to chain: unable to perform wallet recovery: json: cannot unmarshal object into Go value of type string

### ISSUE THREAD

**Issue by tivizi** [btcsuite/btcwallet#729]
### Command
```shell
btcwallet --testnet
```

### Error Logs
```
2021-01-15 15:37:02.676 [INF] BTCW: Version 0.11.0-alpha
2021-01-15 15:37:02.687 [INF] BTCW: Attempting RPC client connection to localhost:18334
2021-01-15 15:37:02.687 [INF] RPCS: Listening on 127.0.0.1:18332
2021-01-15 15:37:02.687 [INF] RPCS: Listening on [::1]:18332
2021-01-15 15:37:02.733 [INF] CHNS: Established connection to RPC server localhost:18334
2021-01-15 15:37:03.791 [INF] WLLT: Opened wallet
2021-01-15 15:37:03.791 [DBG] WLLT: Birthday block has already been verified: height=1903768, hash=0000000037e0ccc0a8863ef979ac45971e0d2ba766d5c44bc4d8731e77989928
2021-01-15 15:37:03.792 [DBG] WLLT: Waiting for chain backend to sync to tip
2021-01-15 15:37:04.793 [DBG] WLLT: Chain backend synced to tip!
2021-01-15 15:37:04.793 [INF] WLLT: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=250
2021-01-15 15:37:04.801 [INF] WLLT: Seed birthday surpassed, starting recovery of wallet from height=1903769 hash=0000000000000016289a6a941be1f4211973bb37a4322b31713ef317c464ab7b with recovery-window=250
2021-01-15 15:37:04.907 [INF] WLLT: Scanning 354 blocks for recoverable addresses
2021-01-15 15:37:05.302 [INF] CHNS: Fetching block height=1903895 hash=00000000000000015e3341518dc9a2e5436bc144553022a1ef0227f16f75dd2e
panic: Unable to synchronize wallet to chain: unable to perform wallet recovery: json: cannot unmarshal object into Go value of type string

goroutine 59 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc0000dc000)
	/home/ujued/Documents/opensource/btcwallet/wallet/chainntfns.go:117 +0x1253
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
	/home/ujued/Documents/opensource/btcwallet/wallet/wallet.go:201 +0x1f4

```
### BTCD Version
```
btcd version 0.21.0-beta
```

**Comment by tivizi** [comment]
With debug, I found that the error occurred here:

https://github.com/btcsuite/btcd/blob/6bd4c64a54faeb343d5e3c1ee5802450a291787f/rpcclient/chain.go#L116

**Comment by jacohend** [comment]
I'm having the same issue:

```
goroutine 259 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc00003e140)
/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20201207233335-415f37ff11a1/wallet/chainntfns.go:117 +0x13fb
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
/go/pkg/mod/github.com/btcsuite/btcwallet@v0.11.1-0.20201207233335-415f37ff11a1/wallet/wallet.go:201 +0x1cb

**Comment by wpaulino** [comment]
@jacohend can you confirm whether it panicked with the same error message `json: cannot unmarshal object into Go value of type string`? This error message should not be possible with the neutrino backend as there's no JSON RPC server.

**Comment by wpaulino** [comment]
@tivizi do you still see this issue with the latest version? This should've been fixed as of https://github.com/btcsuite/btcd/pull/1577, but the dependency wasn't updated until recently.

**Comment by jacohend** [comment]
@wpaulino different error string, but same trace. The log view was purged before I copied the specific error string, but it was some issue with timing out during block retrieval. Around the same time the number of good cf-serving peers went to 0.

**Comment by tivizi** [comment]
@wpaulino ok, i'll try again later. ^0^

**Comment by wpaulino** [comment]
@jacohend if you're able to reproduce this again, please open a new issue with as much detail as possible (logs, panic stacktrace, etc.).

**Comment by Bitcoinnoobie** [comment]
I M getting the same error when i unlock wallet 
"Panic : unable to synchronise wallet to chain :  -1 block number out of range"
