### ISSUE TITLE
chainntfns: Panics during initial sync blow up consumers.

### ISSUE THREAD

**Issue by JoeGruffins** [btcsuite/btcwallet#827]
Specifically, if wallet is locked during recovery btcwallet panics. Trying to use the wallet blows up whatever app is using it if a user simply locks the wallet at the wrong time. I also don't think there is a way to check if btcwallet is currently doing recovery.

I wonder if it's possible to remove the panic logic in `*Wallet.handleChainNotifications` altogether and handle errors more gracefully?

The point of panic that is causing some pain https://github.com/btcsuite/btcwallet/blob/27f244e8454076f5afcc5be6266c3762f902800f/wallet/chainntfns.go#L115-L119

The problematic recovery that we can not currently escape unless shutdown. Locking the wallet here panics. https://github.com/btcsuite/btcwallet/blob/27f244e8454076f5afcc5be6266c3762f902800f/wallet/wallet.go#L665-L792

**Comment by Roasbeef** [comment]
Ah, this makes sense, much of the recent work we've done in `btcwallet` was motivated by `lnd`. For `lnd`, the wallet is unlocked once at start up, then never locked again. 

What's missing here is that we properly thread through a `context.Context` (or something like that), so it can be cancelled to ensure we can do things like unsafe shutdown. 

I agree that panic doesn't really need to be there either, it should be handled gracefully. So we'd either need to try to retry once the wallet is unlocked again, or move it to something periodic tat attempts to sync again once things are clear.

**Comment by chappjc** [comment]
> I wonder if it's possible to remove the panic logic in `*Wallet.handleChainNotifications` altogether and handle errors more gracefully?

This would be good.  There are numerous ways this explicit panic in `handleChainNotifications` can be triggered:
- https://github.com/btcsuite/btcwallet/issues/729 (getblock json response unmarshalling)
- https://github.com/decred/dcrdex/issues/1690 (wallet db closed/shutdown)
- https://github.com/btcsuite/btcwallet/issues/687 (bad json payload in request)
- locking, as in this issue

**Comment by chappjc** [comment]
Just got this recovering a mainnet wallet:

```
panic: unable to synchronize wallet to chain: unable to perform wallet recovery: couldn't retrieve block 00000000000000000004d901bfc6973cad6a39d65f88ac6af77c2c212d1635fd from network

goroutine 4830583 [running]:
github.com/btcsuite/btcwallet/wallet.(*Wallet).handleChainNotifications(0xc0050d6900)
	github.com/btcsuite/btcwallet@v0.16.1/wallet/chainntfns.go:117 +0x1065
created by github.com/btcsuite/btcwallet/wallet.(*Wallet).SynchronizeRPC
	github.com/btcsuite/btcwallet@v0.16.1/wallet/wallet.go:213 +0x25c
```

The neutrino log had no direct error at the time, but shortly prior the node to which that getblock request was made had dropped and reconnected a couple times.

**Comment by JoeGruffins** [comment]
This seems to come up a bit while testing dcrdex. Will attempt to stop the panics as simply as possible if that's alright. Will look through the code some more and come up with a plan.

**Comment by chappjc** [comment]
I hit the `handleChainNotifications` panic twice today, induced by "couldn't retrieve block" both time, so I gave this diff a test.  Naturally it wouldn't reproduce without meddling, so I tried by locking the wallet during rescan.  It worked (mostly)!

```
2023-05-08 17:35:11.535 [INF] BTCW: Recovered addresses from blocks 686014-688013
2023-05-08 17:35:11.535 [ERR] BTCW: unable to synchronize wallet to chain, trying again in one minute: unable to perform wallet recovery: recovery: forced shutdown
2023-05-08 17:35:11.535 [INF] BTCW: The wallet has been locked
... <manually unlocked it here>
2023-05-08 17:35:22.643 [INF] BTCW: The wallet has been unlocked without a time limit
... <retry timer fires>
2023-05-08 17:36:12.536 [INF] BTCW: RECOVERY MODE ENABLED -- rescanning for used addresses with recovery_window=250
2023-05-08 17:36:12.725 [INF] BTCW: Seed birthday surpassed, starting recovery of wallet from height=688014 hash=0000000000000000000ae672f5308b44eb64d263cfad57b1850031c4f3fec3d1 with recovery-window=250
2023-05-08 17:36:12.744 [INF] BTCW: Scanning 2000 blocks for recoverable addresses
```

I was worried it would crash straight away since some methods are strictly call-once, but `w.syncWithChain` is alright it seems.

The issue I had was that my balance was off.  I think it must have failed to register for some addresses after automatically restarting? I still think this is way way better than a panic, esp. since a consumer cannot `recover` it.
